# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.6
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: slochunah30@gmail.com
author_name: Shivesh Lochunah
cloud_provider: none
contract_name: algo_freelance
deployment_language: python
preset_name: production
project_name: AlgoFreelance

